apiVersion: v1
kind: Pod
metadata:
  name: nginx-insufficient-resources
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "500Gi"  # Excessive memory request
        cpu: "1000"
