apiVersion: v1
kind: Pod
metadata:
  name: nginx-bad-liveness-probe
spec:
  containers:
  - name: nginx
    image: nginx:latest
    livenessProbe:
      httpGet:
        path: /wrong-path
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
